### ISSUE TITLE
Add tags manage

### ISSUE THREAD

**Issue by jalog** [node-weixin/node-weixin-user#3]
1. create tag
2. get tags
3. update tag
4. delete tag
5. get by tag
6. batch tagging
7. batch untagging
8. get openid list by tag
9. get blacklist
10. batch blacklist
11. batch unblacklist

**Comment by calidion** [comment]
@jalog 

README update needed.

**Comment by jalog** [comment]
> @jalog
> 
> README update needed.

Updated README.md #6
